variables:
  GIT_STRATEGY: clone
  YARN_CACHE_FOLDER: "$CI_PROJECT_DIR/cache/yarn"

stages:
  - prep
  - build
  - test

include:
  - local: '/gitlab-ci/build/android/.gitlab-ci.yml'
  # - local: '/gitlab-ci/test/android/.gitlab-ci.yml'
